[package]
name = "parquet-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "15.0.0"
tokio = "1.24.1"
arrow = "30.0.1"
arrow-flight = "30.0.1"
async-trait = "0.1.41"
